package com.zbc.pojo;

import java.sql.Timestamp;

public class GroupInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.belong_substance_id
     *
     * @mbg.generated
     */
    private Long belongSubstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.belong_user_id
     *
     * @mbg.generated
     */
    private Long belongUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.gmt_create
     *
     * @mbg.generated
     */
    private Timestamp gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.gmt_modified
     *
     * @mbg.generated
     */
    private Timestamp gmtModified;

    /**
     * 对应的用户信息
     */
    private UserInfoPO userInfoPO;

    public UserInfoPO getUserInfoPO() {
        return userInfoPO;
    }

    public void setUserInfoPO(UserInfoPO userInfoPO) {
        this.userInfoPO = userInfoPO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.id
     *
     * @return the value of group_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.id
     *
     * @param id the value for group_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.belong_substance_id
     *
     * @return the value of group_info.belong_substance_id
     *
     * @mbg.generated
     */
    public Long getBelongSubstanceId() {
        return belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.belong_substance_id
     *
     * @param belongSubstanceId the value for group_info.belong_substance_id
     *
     * @mbg.generated
     */
    public void setBelongSubstanceId(Long belongSubstanceId) {
        this.belongSubstanceId = belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.belong_user_id
     *
     * @return the value of group_info.belong_user_id
     *
     * @mbg.generated
     */
    public Long getBelongUserId() {
        return belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.belong_user_id
     *
     * @param belongUserId the value for group_info.belong_user_id
     *
     * @mbg.generated
     */
    public void setBelongUserId(Long belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.gmt_create
     *
     * @return the value of group_info.gmt_create
     *
     * @mbg.generated
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.gmt_create
     *
     * @param gmtCreate the value for group_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.gmt_modified
     *
     * @return the value of group_info.gmt_modified
     *
     * @mbg.generated
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.gmt_modified
     *
     * @param gmtModified the value for group_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }
}