package com.zbc.pojo;

import java.sql.Timestamp;

public class MsgInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.belong_user_id
     *
     * @mbg.generated
     */
    private Long belongUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.msg_content
     *
     * @mbg.generated
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.is_read
     *
     * @mbg.generated
     */
    private Byte isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.is_aware
     *
     * @mbg.generated
     */
    private Byte isAware;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.gmt_create
     *
     * @mbg.generated
     */
    private Timestamp gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_info.gmt_modified
     *
     * @mbg.generated
     */
    private Timestamp gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.id
     *
     * @return the value of msg_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.id
     *
     * @param id the value for msg_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.belong_user_id
     *
     * @return the value of msg_info.belong_user_id
     *
     * @mbg.generated
     */
    public Long getBelongUserId() {
        return belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.belong_user_id
     *
     * @param belongUserId the value for msg_info.belong_user_id
     *
     * @mbg.generated
     */
    public void setBelongUserId(Long belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.msg_content
     *
     * @return the value of msg_info.msg_content
     *
     * @mbg.generated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.msg_content
     *
     * @param msgContent the value for msg_info.msg_content
     *
     * @mbg.generated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.is_read
     *
     * @return the value of msg_info.is_read
     *
     * @mbg.generated
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.is_read
     *
     * @param isRead the value for msg_info.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.is_aware
     *
     * @return the value of msg_info.is_aware
     *
     * @mbg.generated
     */
    public Byte getIsAware() {
        return isAware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.is_aware
     *
     * @param isAware the value for msg_info.is_aware
     *
     * @mbg.generated
     */
    public void setIsAware(Byte isAware) {
        this.isAware = isAware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.gmt_create
     *
     * @return the value of msg_info.gmt_create
     *
     * @mbg.generated
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.gmt_create
     *
     * @param gmtCreate the value for msg_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_info.gmt_modified
     *
     * @return the value of msg_info.gmt_modified
     *
     * @mbg.generated
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_info.gmt_modified
     *
     * @param gmtModified the value for msg_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }
}