package com.zbc.pojo;

import java.sql.Timestamp;

public class SubstanceLocationPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.belong_substance_id
     *
     * @mbg.generated
     */
    private Long belongSubstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.location_text
     *
     * @mbg.generated
     */
    private String locationText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    private Integer distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.gmt_create
     *
     * @mbg.generated
     */
    private Timestamp gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_location.gmt_modified
     *
     * @mbg.generated
     */
    private Timestamp gmtModified;

    /**
     * belongSubstanceId 对应的信息
     */
    private SubstanceInfoPO substanceInfoPO;

    public Integer getDistance() {
        return distance;
    }

    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    public SubstanceInfoPO getSubstanceInfoPO() {
        return substanceInfoPO;
    }

    public void setSubstanceInfoPO(SubstanceInfoPO substanceInfoPO) {
        this.substanceInfoPO = substanceInfoPO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.id
     *
     * @return the value of substance_location.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.id
     *
     * @param id the value for substance_location.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.belong_substance_id
     *
     * @return the value of substance_location.belong_substance_id
     *
     * @mbg.generated
     */
    public Long getBelongSubstanceId() {
        return belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.belong_substance_id
     *
     * @param belongSubstanceId the value for substance_location.belong_substance_id
     *
     * @mbg.generated
     */
    public void setBelongSubstanceId(Long belongSubstanceId) {
        this.belongSubstanceId = belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.location_text
     *
     * @return the value of substance_location.location_text
     *
     * @mbg.generated
     */
    public String getLocationText() {
        return locationText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.location_text
     *
     * @param locationText the value for substance_location.location_text
     *
     * @mbg.generated
     */
    public void setLocationText(String locationText) {
        this.locationText = locationText == null ? null : locationText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.longitude
     *
     * @return the value of substance_location.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.longitude
     *
     * @param longitude the value for substance_location.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.latitude
     *
     * @return the value of substance_location.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.latitude
     *
     * @param latitude the value for substance_location.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.gmt_create
     *
     * @return the value of substance_location.gmt_create
     *
     * @mbg.generated
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.gmt_create
     *
     * @param gmtCreate the value for substance_location.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_location.gmt_modified
     *
     * @return the value of substance_location.gmt_modified
     *
     * @mbg.generated
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_location.gmt_modified
     *
     * @param gmtModified the value for substance_location.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }
}