package org.zbc.pojo;

import java.sql.Timestamp;

public class SubstanceContentPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_content.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_content.belong_substance_id
     *
     * @mbg.generated
     */
    private Long belongSubstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_content.gmt_create
     *
     * @mbg.generated
     */
    private Timestamp gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_content.gmt_modified
     *
     * @mbg.generated
     */
    private Timestamp gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_content.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_content.id
     *
     * @return the value of substance_content.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_content.id
     *
     * @param id the value for substance_content.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_content.belong_substance_id
     *
     * @return the value of substance_content.belong_substance_id
     *
     * @mbg.generated
     */
    public Long getBelongSubstanceId() {
        return belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_content.belong_substance_id
     *
     * @param belongSubstanceId the value for substance_content.belong_substance_id
     *
     * @mbg.generated
     */
    public void setBelongSubstanceId(Long belongSubstanceId) {
        this.belongSubstanceId = belongSubstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_content.gmt_create
     *
     * @return the value of substance_content.gmt_create
     *
     * @mbg.generated
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_content.gmt_create
     *
     * @param gmtCreate the value for substance_content.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_content.gmt_modified
     *
     * @return the value of substance_content.gmt_modified
     *
     * @mbg.generated
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_content.gmt_modified
     *
     * @param gmtModified the value for substance_content.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_content.content
     *
     * @return the value of substance_content.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_content.content
     *
     * @param content the value for substance_content.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}