package org.zbc.pojo;

import java.sql.Timestamp;

public class SubstanceInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.belong_user_id
     *
     * @mbg.generated
     */
    private Long belongUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.is_realistic
     *
     * @mbg.generated
     */
    private Byte isRealistic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.locale
     *
     * @mbg.generated
     */
    private String locale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.is_anonymous_permit
     *
     * @mbg.generated
     */
    private Byte isAnonymousPermit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.is_restricted
     *
     * @mbg.generated
     */
    private Byte isRestricted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.join_code
     *
     * @mbg.generated
     */
    private String joinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.people_restrict
     *
     * @mbg.generated
     */
    private Short peopleRestrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.gmt_create
     *
     * @mbg.generated
     */
    private Timestamp gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column substance_info.gmt_modified
     *
     * @mbg.generated
     */
    private Timestamp gmtModified;

    private Byte isVerified;

    private String unverifiedFactor;

    public Byte getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Byte isVerified) {
        this.isVerified = isVerified;
    }

    public String getUnverifiedFactor() {
        return unverifiedFactor;
    }

    public void setUnverifiedFactor(String unverifiedFactor) {
        this.unverifiedFactor = unverifiedFactor;
    }

    private SubstanceContentPO substanceContentPO;

    public SubstanceContentPO getSubstanceContentPO() {
        return substanceContentPO;
    }

    public void setSubstanceContentPO(SubstanceContentPO substanceContentPO) {
        this.substanceContentPO = substanceContentPO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.id
     *
     * @return the value of substance_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.id
     *
     * @param id the value for substance_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.belong_user_id
     *
     * @return the value of substance_info.belong_user_id
     *
     * @mbg.generated
     */
    public Long getBelongUserId() {
        return belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.belong_user_id
     *
     * @param belongUserId the value for substance_info.belong_user_id
     *
     * @mbg.generated
     */
    public void setBelongUserId(Long belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.subject
     *
     * @return the value of substance_info.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.subject
     *
     * @param subject the value for substance_info.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.summary
     *
     * @return the value of substance_info.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.summary
     *
     * @param summary the value for substance_info.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.cover
     *
     * @return the value of substance_info.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.cover
     *
     * @param cover the value for substance_info.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.is_realistic
     *
     * @return the value of substance_info.is_realistic
     *
     * @mbg.generated
     */
    public Byte getIsRealistic() {
        return isRealistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.is_realistic
     *
     * @param isRealistic the value for substance_info.is_realistic
     *
     * @mbg.generated
     */
    public void setIsRealistic(Byte isRealistic) {
        this.isRealistic = isRealistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.locale
     *
     * @return the value of substance_info.locale
     *
     * @mbg.generated
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.locale
     *
     * @param locale the value for substance_info.locale
     *
     * @mbg.generated
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.is_anonymous_permit
     *
     * @return the value of substance_info.is_anonymous_permit
     *
     * @mbg.generated
     */
    public Byte getIsAnonymousPermit() {
        return isAnonymousPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.is_anonymous_permit
     *
     * @param isAnonymousPermit the value for substance_info.is_anonymous_permit
     *
     * @mbg.generated
     */
    public void setIsAnonymousPermit(Byte isAnonymousPermit) {
        this.isAnonymousPermit = isAnonymousPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.is_restricted
     *
     * @return the value of substance_info.is_restricted
     *
     * @mbg.generated
     */
    public Byte getIsRestricted() {
        return isRestricted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.is_restricted
     *
     * @param isRestricted the value for substance_info.is_restricted
     *
     * @mbg.generated
     */
    public void setIsRestricted(Byte isRestricted) {
        this.isRestricted = isRestricted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.join_code
     *
     * @return the value of substance_info.join_code
     *
     * @mbg.generated
     */
    public String getJoinCode() {
        return joinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.join_code
     *
     * @param joinCode the value for substance_info.join_code
     *
     * @mbg.generated
     */
    public void setJoinCode(String joinCode) {
        this.joinCode = joinCode == null ? null : joinCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.people_restrict
     *
     * @return the value of substance_info.people_restrict
     *
     * @mbg.generated
     */
    public Short getPeopleRestrict() {
        return peopleRestrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.people_restrict
     *
     * @param peopleRestrict the value for substance_info.people_restrict
     *
     * @mbg.generated
     */
    public void setPeopleRestrict(Short peopleRestrict) {
        this.peopleRestrict = peopleRestrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.gmt_create
     *
     * @return the value of substance_info.gmt_create
     *
     * @mbg.generated
     */
    public Timestamp getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.gmt_create
     *
     * @param gmtCreate the value for substance_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column substance_info.gmt_modified
     *
     * @return the value of substance_info.gmt_modified
     *
     * @mbg.generated
     */
    public Timestamp getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column substance_info.gmt_modified
     *
     * @param gmtModified the value for substance_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }
}