package org.zbc.dao;

import org.zbc.pojo.SubstanceInfoPO;

public interface SubstanceInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    int insert(SubstanceInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    int insertSelective(SubstanceInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    SubstanceInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SubstanceInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubstanceInfoPO record);

    /**
     * substance_info 和 substance_content 两表联合查询
     * @param id
     * @return
     */
    SubstanceInfoPO selectIncludeContent(Long id);
}