package com.zbc.service;

import com.zbc.pojo.GroupInfoPO;
import com.zbc.pojo.PagingInfo;

import java.util.List;

public interface GroupInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 根据所属的substance ID 删除指定记录
     * @param id
     * @return
     */
    int deleteByBelongSubstanceId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    //int insert(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int insertSelective(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    //GroupInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    //int updateByPrimaryKeySelective(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    //int updateByPrimaryKey(GroupInfoPO record);

    /**
     * 根据substance的id获得所有加入此id的用户信息
     * @param id
     * @return
     */
    List<GroupInfoPO> listBySubstanceId(Long id);

    /**
     * 根据用户id 找出加入的group 信息
     * @param pagingInfo
     * @return
     */
    List<GroupInfoPO> listByBelongUserId(PagingInfo pagingInfo);

    /**
     * 根据用户id获得该用户加入多少的兴趣组
     * @param id
     * @return
     */
    int countByUserId(Long id);

    /**
     * 根据用户id和substance id查询该用户是否加入了指定substance
     * @param record
     * @return
     */
    GroupInfoPO selectByBothId(GroupInfoPO record);
}
