package com.zbc.service;

import com.zbc.pojo.PagingInfo;
import com.zbc.pojo.SubstanceLocationPO;

import java.util.List;

public interface SubstanceLocationService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    int insert(SubstanceLocationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    int insertSelective(SubstanceLocationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    SubstanceLocationPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SubstanceLocationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubstanceLocationPO record);

    /**
     * 根据经纬度计算距离小于 的前30个
     * @return
     */
    List<SubstanceLocationPO> listByDistance(PagingInfo pagingInfo);
}
