package com.zbc.dao;

import com.zbc.pojo.GroupInfoPO;
import org.mybatis.spring.annotation.MapperScan;

import java.util.List;

@MapperScan
public interface GroupInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int insert(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int insertSelective(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    GroupInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupInfoPO record);

    /**
     * 根据substance的id获得所有加入此id的用户信息
     * @param id
     * @return
     */
    List<GroupInfoPO> listBySubstanceId(Long id);

    /**
     * 根据用户id获得该用户加入多少的兴趣组
     * @param id
     * @return
     */
    int countByUserId(Long id);

    /**
     * 根据用户id和substance id查询该用户是否加入了指定substance
     * @param id
     * @return
     */
    GroupInfoPO selectByBothId(GroupInfoPO record);
}