package com.zbc.dao;

import org.mybatis.spring.annotation.MapperScan;
import com.zbc.pojo.SubstanceContentPO;

@MapperScan
public interface SubstanceContentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int insert(SubstanceContentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int insertSelective(SubstanceContentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    SubstanceContentPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SubstanceContentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SubstanceContentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substance_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubstanceContentPO record);
}