package com.zbc.dao;

import com.zbc.pojo.UserInfoPO;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface UserInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int insertByRegister(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int insertSelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    UserInfoPO selectByPrimaryKey(Long id);

    /**
     * 通过指定少量用户信息获取特定用户信息
     * @param record
     * @return
     */
    UserInfoPO selectByUserInfo(UserInfoPO record);

    /**
     * 通过邮箱查询用户信息
     * @param email
     * @return
     */
    UserInfoPO selectByEmail(String email);

    /**
     * 通过邮箱和注册代码查询用户
     * @param record
     * @return
     */
    UserInfoPO selectByCodeAndEmail(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfoPO record);
}